export const GET_INVESTMENTS_REQUEST = 'GET_INVESTMENTS_REQUEST';
export const GET_INVESTMENTS_REQUEST_SUCCESS = 'GET_INVESTMENTS_REQUEST_SUCCESS';
export const GET_INVESTMENTS_REQUEST_FAILURE = 'GET_INVESTMENTS_REQUEST_FAILURE';

export const GET_INVESTMENT_REQUEST = 'GET_INVESTMENT_REQUEST';
export const GET_INVESTMENT_REQUEST_SUCCESS = 'GET_INVESTMENT_REQUEST_SUCCESS';
export const GET_INVESTMENT_REQUEST_FAILURE = 'GET_INVESTMENT_REQUEST_FAILURE';

export const EDIT_INVESTMENT_REQUEST = 'EDIT_INVESTMENT_REQUEST';
export const EDIT_INVESTMENT_REQUEST_SUCCESS = 'EDIT_INVESTMENT_REQUEST_SUCCESS';
export const EDIT_INVESTMENT_REQUEST_FAILURE = 'EDIT_INVESTMENT_REQUEST_FAILURE';
export const RESET_EDIT_INVESTMENT_REQUEST = 'RESET_EDIT_INVESTMENT_REQUEST';
