export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_REQUEST_SUCCESS = 'IMAGE_UPLOAD_REQUEST_SUCCESS';
export const IMAGE_UPLOAD_REQUEST_FAILURE = 'IMAGE_UPLOAD_REQUEST_FAILURE';

export const IMAGE_UPLOAD_PERCENTAGE = 'IMAGE_UPLOAD_PERCENTAGE';
