export const GET_RETURNS_REQUEST = 'GET_RETURNS_REQUEST';
export const GET_RETURNS_REQUEST_SUCCESS = 'GET_RETURNS_REQUEST_SUCCESS';
export const GET_RETURNS_REQUEST_FAILURE = 'GET_RETURNS_REQUEST_FAILURE';

export const GET_RETURN_REQUEST = 'GET_RETURN_REQUEST';
export const GET_RETURN_REQUEST_SUCCESS = 'GET_RETURN_REQUEST_SUCCESS';
export const GET_RETURN_REQUEST_FAILURE = 'GET_RETURN_REQUEST_FAILURE';

export const EDIT_RETURNS_REQUEST = 'EDIT_RETURNS_REQUEST';
export const EDIT_RETURNS_REQUEST_SUCCESS = 'EDIT_RETURNS_REQUEST_SUCCESS';
export const EDIT_RETURNS_REQUEST_FAILURE = 'EDIT_RETURNS_REQUEST_FAILURE';
export const RESET_EDIT_RETURNS_REQUEST = 'RESET_EDIT_RETURNS_REQUEST';
