export const ADD_INVESTOR_REQUEST = 'ADD_INVESTOR_REQUEST';
export const ADD_INVESTOR_REQUEST_SUCCESS = 'ADD_INVESTOR_REQUEST_SUCCESS';
export const ADD_INVESTOR_REQUEST_FAILURE = 'ADD_INVESTOR_REQUEST_FAILURE';
export const RESET_INVESTOR_REQUEST = 'RESET_INVESTOR_REQUEST';

export const EDIT_INVESTOR_REQUEST = 'EDIT_INVESTOR_REQUEST';
export const EDIT_INVESTOR_REQUEST_SUCCESS = 'EDIT_INVESTOR_REQUEST_SUCCESS';
export const EDIT_INVESTOR_REQUEST_FAILURE = 'EDIT_INVESTOR_REQUEST_FAILURE';
export const RESET_EDIT_INVESTOR_REQUEST = 'RESET_EDIT_INVESTOR_REQUEST';

export const GET_INVESTORS_REQUEST = 'GET_INVESTORS_REQUEST';
export const GET_INVESTORS_REQUEST_SUCCESS = 'GET_INVESTORS_REQUEST_SUCCESS';
export const GET_INVESTORS_REQUEST_FAILURE = 'GET_INVESTORS_REQUEST_FAILURE';

export const GET_INVESTOR_REQUEST = 'GET_INVESTOR_REQUEST';
export const GET_INVESTOR_REQUEST_SUCCESS = 'GET_INVESTOR_REQUEST_SUCCESS';
export const GET_INVESTOR_REQUEST_FAILURE = 'GET_INVESTOR_REQUEST_FAILURE';
export const SET_CURRENT_INVESTOR = 'SET_CURRENT_INVESTOR';

export const ADD_INVESTMENT_REQUEST = 'ADD_INVESTMENT_REQUEST';
export const ADD_INVESTMENT_REQUEST_SUCCESS = 'ADD_INVESTMENT_REQUEST_SUCCESS';
export const ADD_INVESTMENT_REQUEST_FAILURE = 'ADD_INVESTMENT_REQUEST_FAILURE';
export const RESET_INVESTMENT_REQUEST = 'RESET_INVESTMENT_REQUEST';

export const GET_INVESTMENT_REQUEST = 'GET_INVESTMENT_REQUEST';
export const GET_INVESTMENT_REQUEST_SUCCESS = 'GET_INVESTMENT_REQUEST_SUCCESS';
export const GET_INVESTMENT_REQUEST_FAILURE = 'GET_INVESTMENT_REQUEST_FAILURE';

export const GET_INVESTMENT_RETURNS_REQUEST = 'GET_INVESTMENT_RETURNS_REQUEST';
export const GET_INVESTMENT_RETURNS_REQUEST_SUCCESS = 'GET_INVESTMENT_RETURNS_REQUEST_SUCCESS';
export const GET_INVESTMENT_RETURNS_REQUEST_FAILURE = 'GET_INVESTMENT_RETURNS_REQUEST_FAILURE';

export const GET_INVESTOR_INVESTMENT_REQUEST = 'GET_INVESTOR_INVESTMENT_REQUEST';
export const GET_INVESTOR_INVESTMENT_REQUEST_SUCCESS = 'GET_INVESTOR_INVESTMENT_REQUEST_SUCCESS';
export const GET_INVESTOR_INVESTMENT_REQUEST_FAILURE = 'GET_INVESTOR_INVESTMENT_REQUEST_FAILURE';

export const GET_INVESTOR_HISTORY_REQUEST = 'GET_INVESTOR_HISTORY_REQUEST';
export const GET_INVESTOR_HISTORY_REQUEST_SUCCESS = 'GET_INVESTOR_HISTORY_REQUEST_SUCCESS';
export const GET_INVESTOR_HISTORY_REQUEST_FAILURE = 'GET_INVESTOR_HISTORY_REQUEST_FAILURE';

export const GET_INVESTOR_RETURNS_REQUEST = 'GET_INVESTOR_RETURNS_REQUEST';
export const GET_INVESTOR_RETURNS_REQUEST_SUCCESS = 'GET_INVESTOR_RETURNS_REQUEST_SUCCESS';
export const GET_INVESTOR_RETURNS_REQUEST_FAILURE = 'GET_INVESTOR_RETURNS_REQUEST_FAILURE';

export const CONFIRM_RETURNS_REQUEST = 'CONFIRM_RETURNS_REQUEST';
export const CONFIRM_RETURNS_REQUEST_SUCCESS = 'CONFIRM_RETURNS_REQUEST_SUCCESS';
export const CONFIRM_RETURNS_REQUEST_FAILURE = 'CONFIRM_RETURNS_REQUEST_FAILURE';
