export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILURE = 'REGISTER_REQUEST_FAILURE';

export const REQUEST_USER_REQUEST = 'REQUEST_USER_REQUEST';
export const REQUEST_USER_REQUEST_SUCCESS = 'REQUEST_USER_REQUEST_SUCCESS';
export const REQUEST_USER_REQUEST_FAILURE = 'REQUEST_USER_REQUEST_FAILURE';

export const APPROVE_USER = 'APPROVE_USER';
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_FAILURE = 'APPROVE_USER_FAILURE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
