export const banksArray = [
  { id: '1', name: 'Access Bank', value: '044' },
  { id: '2', name: 'Citibank', value: '023' },
  { id: '3', name: 'Diamond Bank', value: '063' },
  { id: '5', name: 'Ecobank Nigeria', value: '050' },
  { id: '6', name: 'Fidelity Bank Nigeria', value: '070' },
  { id: '7', name: 'First Bank of Nigeria', value: '011' },
  { id: '8', name: 'First City Monument Bank', value: '214' },
  { id: '9', name: 'Guaranty Trust Bank', value: '058' },
  { id: '10', name: 'Heritage Bank Plc', value: '030' },
  { id: '11', name: 'Jaiz Bank', value: '301' },
  { id: '12', name: 'Keystone Bank Limited', value: '082' },
  { id: '13', name: 'Providus Bank Plc', value: '101' },
  { id: '14', name: 'Polaris Bank', value: '076' },
  { id: '15', name: 'Stanbic IBTC Bank Nigeria Limited', value: '221' },
  { id: '16', name: 'Standard Chartered Bank', value: '068' },
  { id: '17', name: 'Sterling Bank', value: '232' },
  { id: '18', name: 'Suntrust Bank Nigeria Limited', value: '100' },
  { id: '19', name: 'Union Bank of Nigeria', value: '032' },
  { id: '20', name: 'United Bank for Africa', value: '033' },
  { id: '21', name: 'Unity Bank Plc', value: '215' },
  { id: '22', name: 'Wema Bank', value: '035' },
  { id: '23', name: 'Zenith Bank', value: '057' },
];
