export const INVITE_ADMIN_STAFF_REQUEST = 'INVITE_ADMIN_STAFF_REQUEST';
export const INVITE_ADMIN_STAFF_REQUEST_SUCCESS = 'INVITE_ADMIN_STAFF_REQUEST_SUCCESS';
export const INVITE_ADMIN_STAFF_REQUEST_FAILURE = 'INVITE_ADMIN_STAFF_REQUEST_FAILURE';
export const RESET_ADMIN_STAFF_INVITE = 'RESET_ADMIN_STAFF_INVITE';

export const GET_ADMIN_STAFF_REQUEST = 'GET_ADMIN_STAFF_REQUEST';
export const GET_ADMIN_STAFF_REQUEST_SUCCESS = 'GET_ADMIN_STAFF_REQUEST_SUCCESS';
export const GET_ADMIN_STAFF_REQUEST_FAILURE = 'GET_ADMIN_STAFF_REQUEST_FAILURE';

export const CANCEL_ADMIN_STAFF_INVITE_REQUEST = 'CANCEL_ADMIN_STAFF_INVITE_REQUEST';
export const CANCEL_ADMIN_STAFF_INVITE_REQUEST_SUCCESS =
  'CANCEL_ADMIN_STAFF_INVITE_REQUEST_SUCCESS';
export const CANCEL_ADMIN_STAFF_INVITE_REQUEST_FAILURE =
  'CANCEL_ADMIN_STAFF_INVITE_REQUEST_FAILURE';
export const RESET_CANCEL_ADMIN_STAFF_INVITE = 'RESET_CANCEL_ADMIN_STAFF_INVITE';
