export const ADD_BUSINESS_REQUEST = 'ADD_BUSINESS_REQUEST';
export const ADD_BUSINESS_REQUEST_SUCCESS = 'ADD_BUSINESS_REQUEST_SUCCESS';
export const ADD_BUSINESS_REQUEST_FAILURE = 'ADD_BUSINESS_REQUEST_FAILURE';

export const SET_CURRENT_BUSINESS = 'SET_CURRENT_BUSINESS';

export const GET_BUSINESSES_REQUEST = 'GET_BUSINESSES_REQUEST';
export const GET_BUSINESSES_REQUEST_SUCCESS = 'GET_BUSINESSES_REQUEST_SUCCESS';
export const GET_BUSINESSES_REQUEST_FAILURE = 'GET_BUSINESSES_REQUEST_FAILURE';

export const GET_BUSINESS_HISTORY_REQUEST = 'GET_BUSINESS_HISTORY_REQUEST';
export const GET_BUSINESS_HISTORY_REQUEST_SUCCESS = 'GET_BUSINESS_HISTORY_REQUEST_SUCCESS';
export const GET_BUSINESS_HISTORY_REQUEST_FAILURE = 'GET_BUSINESS_HISTORY_REQUEST_FAILURE';

export const GET_BUSINESS_OVERVIEW_REQUEST = 'GET_BUSINESS_OVERVIEW_REQUEST';
export const GET_BUSINESS_OVERVIEW_REQUEST_SUCCESS = 'GET_BUSINESS_OVERVIEW_REQUEST_SUCCESS';
export const GET_BUSINESS_OVERVIEW_REQUEST_FAILURE = 'GET_BUSINESS_OVERVIEW_REQUEST_FAILURE';

export const SET_BUSINESS_OVERVIEW_OPTION = 'SET_BUSINESS_OVERVIEW_OPTION';
